[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { version = "0.19.1" }
env_logger = "0.10"
serde = "1.0"
bonsai-sdk = "0.5.1"
anyhow = "1.0"
hex = "0.4"
bincode = "1.0"
